### PR TITLE
Fix error with toolshed get_ordered_installable_revisions and get_repository_revision_install_info

### PR DESCRIPTION
**Pull request by abretaud**
This fixes the following error I get when trying to get the list of revisions for a tool from the toolshed:
```
  File "/home/abretaud/miniconda3/lib/python3.7/site-packages/bioblend/toolshed/repositories/__init__.py", line 144, in get_ordered_installable_revisions
    url = self.url + '/get_ordered_installable_revisions'
AttributeError: 'ToolShedRepositoryClient' object has no attribute 'url'
```

What surprises me is that this usegalaxy.eu script should be failing without this patch, but somehow tools get updated: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/scripts/update-tool.py#L35

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think I broke this in commit 51f36db65bd0c95e9ecf73a9dd4a40bde5e5d1fd , which is not in a BioBlend release yet, which should explain why that script works.

**Comment by abretaud** [comment]
Ah yes you're right, I installed from github apparently

File: bioblend/toolshed/repositories/__init__.py [hunk 1]
```diff
@@ -141,7 +141,7 @@ def get_ordered_installable_revisions(self, name, owner):
         :rtype: list
         :return: List of changeset revision hash strings from oldest to newest
         """
-        url = self.url + '/get_ordered_installable_revisions'
+        url = self.gi.url + '/repositories/get_ordered_installable_revisions'
```
Comment (nsoranzo) [inline bioblend/toolshed/repositories/__init__.py]:
```suggestion
        url = self._make_url() + '/get_ordered_installable_revisions'
```

File: bioblend/toolshed/repositories/__init__.py [hunk 2]
```diff
@@ -222,7 +222,7 @@ def get_repository_revision_install_info(self, name, owner,
                                                  'type': 'package',
                                                  'version': '0.1.18'}}]}]
         """
-        url = self.url + '/get_repository_revision_install_info'
+        url = self.gi.url + '/repositories/get_repository_revision_install_info'
```
Comment (nsoranzo) [inline bioblend/toolshed/repositories/__init__.py]:
```suggestion
        url = self._make_url() + '/get_repository_revision_install_info'
```

**Comment by nsoranzo** [comment]
Thanks! We need to add tests for this module one day...
